application:
    simple-training:
        access-key: "AIzaSyBddGILQm5KY5hrQ-80vXi2xl8Jam-xgBc"
        base-url: "http://localhost:8190"
        client-id: "321116716041-229h0d82evq6mk7o3q2lj4i9ogji2adq.apps.googleusercontent.com"

spring:
    datasource:
        initialize=true
        url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName=org.h2.Driver
        username=sa
        password=x
    h2:
        console:
             enabled=true

server:
    port: 8190